#ifndef TKTUSBMANAGER_DEF_USB_ENDPOINTS_H
#define TKTUSBMANAGER_DEF_USB_ENDPOINTS_H

typedef struct TktUsbEndpoints TktUsbEndpoints;

enum {
    MAX_USER_ENDPOINTS_COUNT = 8,
};

#endif  // TKTUSBMANAGER_DEF_USB_ENDPOINTS_H
